version: '3.8'

services:
  maven:
    image: maven:3.8.6-eclipse-temurin-17
    volumes:
      - ./:/app
      - maven-repo:/root/.m2
    working_dir: /app
    command: mvn clean install -DskipTests

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rate-limiter-dev
    volumes:
      - ./:/app
      - maven-repo:/root/.m2
    ports:
      - "8080:8080"
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    depends_on:
      - maven
    command: ./mvnw spring-boot:run

volumes:
  maven-repo: